### ISSUE TITLE
Baud rate mismatch in wiki

### ISSUE THREAD

**Issue by sguillia** [drotek/SMARTNAV-RTK#11]
Hello,

There is a little error in the wiki on the [manual configuration page](https://github.com/drotek/SMARTNAV-RTK/wiki/Manual-configuration).

> `ttyUSB0:38400:8:n:1:off` for a radio link plugged on the external USB port, baudrate 57600, 8 bits, no parity check, 1 stop bit, no flow control

Baud rates should be both the same.

Cheers

**Comment by klopezal** [comment]
Hello, 

Thanks, corrected ! :)
