### ISSUE TITLE
Link broken in Wiki

### ISSUE THREAD

**Issue by kikislater** [drotek/SMARTNAV-RTK#12]
Even if I know how to connect with ssh to the board, there is a problem in wiki : 
This link revert nothing, please update for other users => (page https://github.com/drotek/SMARTNAV-RTK/wiki/Setting-up-data-links#tcp-link ) http://drotek.com/wiki/accessing-the-intel-edison/?lang=en

**Comment by klopezal** [comment]
Thanks, it is corrected in our website. Due to migration of our website we have to manually review all the links and the images.
