### ISSUE TITLE
Please update Wiki : Images not present

### ISSUE THREAD

**Issue by kikislater** [drotek/SMARTNAV-RTK#15]
This folder was removed  : https://drotek.com/wiki/wp-content/uploads/2016/02/
So pictures present in Wiki github and drotek website is not available ...

Please update

**Comment by chenmanjia** [comment]
I open the web "https://drotek.com/wiki/wp-content/uploads/2016/02/",but it show 404 "Page non trouvée"

**Comment by chenmanjia** [comment]
please give me available web ，thanks.

**Comment by klopezal** [comment]
Hello, we have encountered some problems with migration, it is work in progress and will be solved within the week.

**Comment by klopezal** [comment]
Now solved, thanks for your patience.
