### ISSUE TITLE
Configuration of Drotek Livebox is in config file

### ISSUE THREAD

**Issue by kikislater** [drotek/SMARTNAV-RTK#2]
# cat /etc/wpa_supplicant/wpa_supplicant.conf
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
config_methods=virtual_push_button virtual_display push_button keypad
update_config=1
fast_reauth=1
device_name=Edison
manufacturer=Intel
model_name=Edison

network={
  ssid="Livebox-b228"
  
  key_mgmt=WPA-PSK
  pairwise=CCMP TKIP
  group=CCMP TKIP WEP104 WEP40
  eap=TTLS PEAP TLS
  psk="drotekwifi"
}

**Comment by klopezal** [comment]
This is because each device is completely tested before shipment. Do you think it is a problem?

**Comment by kikislater** [comment]
no but your share you wifi for everyone. Should be better to test over ethernet ...
