### ISSUE TITLE
Need gps time in the interface to check what is wrong

### ISSUE THREAD

**Issue by kikislater** [drotek/SMARTNAV-RTK#4]
Sync command is usefull but we have to do over internet connection otherwise timestamp is completely wacky !
A good option is to add time to webconsole ...

**Comment by klopezal** [comment]
Completely true, we have corrected it this way : a daemon checks for GPS sync to get time before allowing any RTK service to boot. This way system is always synchronized automatically.

**Comment by kikislater** [comment]
So is it in the next release ?

**Comment by klopezal** [comment]
Yes !
