### ISSUE TITLE
Add how to use update to the wiki

### ISSUE THREAD

**Issue by kikislater** [drotek/SMARTNAV-RTK#5]
There is an option to update the software I think to the smartnav but it's not in the wiki user page.
Please add how to update ... I'm afraid to brick the receiver !

**Comment by klopezal** [comment]
Good point, will be added!

**Comment by klopezal** [comment]
Done [here](https://github.com/drotek/SMARTNAV-RTK/wiki/Update-the-board)

**Comment by kikislater** [comment]
thanks
