### ISSUE TITLE
Add coordinate to the base into the webconsole

### ISSUE THREAD

**Issue by kikislater** [drotek/SMARTNAV-RTK#6]
When we connect to the webconsole, we could not check what are coordinates have the base. Furthermore we have to add to the config file of rover, it should be good to add base coordinate to interface.

**Comment by klopezal** [comment]
You can always check base's position inside Config tab. We have added in next release an automatic averaging of base's postions to generate an automatic position.

**Comment by kikislater** [comment]
In config tab ? Where ?

Nice for the next release !

**Comment by klopezal** [comment]
On Rover side, under Config tab you can read ant2-pos1, ant2-pos2 and ant3-pos3 (latitude, longitude and height).

**Comment by kikislater** [comment]
I never get a fix with these modules. Waiting a long time outside (a couple of hours). Goind to push a ticket on drtotek website

**Comment by klopezal** [comment]
Do you get float solution easily? What is your setup exactly?

**Comment by klopezal** [comment]
Solved
